name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      -
        name: Import GPG key
        id: import_gpg
        uses: paultyng/ghaction-import-gpg@v2.1.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: Set the user terminal
        run: export GPG_TTY=$(tty)
      - name: Install KPS client
        run: mkdir -p ./generated/kps_cloud_api_swagger \
          mkdir -p ./bin
          curl -o ./generated/kps_api.json https://karbon.nutanix.com/kps_api_full.json
          curl -o ./bin/swagger -L'#' https://github.com/go-swagger/go-swagger/releases/download/v0.21.0/swagger_darwin_amd64
          chmod +x ./bin/swagger
          ./bin/swagger generate client -t ./generated/kps_cloud_api_swagger -f ./generated/kps_api.json -A sherlock
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}